language: elixir
elixir:
  - 1.10.1
node_js:
  - 12

otp_release:
  - 21.0

env:
  global:
    - LANG=en_US.UTF-8
    - LANGUAGE=en_US:en
    - LC_ALL=en_US.UTF-8

services:
  - postgresql

before_install:
  - nvm install 12

before_script:
  - mix deps.get
  - pushd assets && nvm use 12 && yarn install && popd
  - cp config/test.travis.exs config/test.exs
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

script:
  - nvm use 12 && mix coveralls.travis

after_failure:
  - ./travis/post_build_results

after_success:
  - ./travis/post_build_results
