version: '3.1'

services:
  whats_where_test_runner:
    build:
      context: "../../"
      dockerfile: "docker/testing/Dockerfile"
    volumes:
      - .:/home/elixir/test_results/
    depends_on:
      - whats_where_test_db
    links:
      - whats_where_test_db
  whats_where_test_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    expose:
      - 5432
