#!/bin/bash

image_host="treyedocker"
tag=`git rev-parse HEAD`
tag_name=whats_where_deploy:deploy_${tag}
compose_file_string=`cat docker/deploy/docker-compose.template.yml`
image_name=${image_host}/${tag_name}

echo "Git build SHA will be ${tag}"
echo "Local image tag will be called ${tag_name}"
echo "Built image will be pushed as ${image_name}"
echo "You will find the compose file at: docker_releases/${tag}/docker-compose.yml"

rm -rf ./whats_where_release.zip
rm -rf ./docker_releases
rm -rf ./codedeploy_releases
mkdir docker_releases
mkdir codedeploy_releases

set -x
./docker/docker_compile_release && \
  cp docker/release/whats_where_release.zip ./ && \
  docker build -f docker/deploy/Dockerfile -t ${tag_name} . && \
  docker tag ${tag_name} ${image_name} && \
  docker push ${image_name}

set +x

echo "${compose_file_string/SUBSTITUTE_RELEASE_IMAGE_NAME_HERE/$image_name}" > docker_releases/docker-compose.yml.1
compose_host_file_string=`cat ./docker_releases/docker-compose.yml.1`
echo "${compose_host_file_string/SUBSTITUTE_DEPLOY_HOST_NAME_HERE/$TRAVIS_DEPLOY_HOSTNAME}" > docker_releases/docker-compose.yml

deploy_file_string=`cat ./docker/deploy/deploy`
echo "${deploy_file_string/SUBSTITUTE_RELEASE_IMAGE_NAME_HERE/$image_name}" > docker_releases/deploy
chmod u+x ./docker_releases/deploy
chmod o+x ./docker_releases/deploy

cp ./docker/deploy/appspec.yml ./docker_releases/

pushd docker_releases && zip whats-where.zip deploy docker-compose.yml appspec.yml && popd
cp -f ./docker_releases/whats-where.zip ./codedeploy_releases/