#!/bin/bash

rm -f docker/release/whats_where_release.zip
docker-compose -f docker/release/docker-compose.yml build release_builder && docker-compose -f docker/release/docker-compose.yml run --rm release_builder /bin/bash -cl ./release
