#!/bin/bash

image_host="treyedocker"
tag=`git rev-parse HEAD`
tag_name=whats_where_deploy:deploy_${tag}
compose_file_string=`cat docker/deploy/docker-compose.template.yml`
image_name=${image_host}/${tag_name}

echo "Git build SHA will be ${tag}"
echo "Local image tag will be called ${tag_name}"
echo "Built image will be pushed as ${image_name}"
echo "You will find the compose file at: docker_releases/${tag}/docker-compose.yml"

rm -rf ./whats_where_release.zip
rm -rf ./docker_releases
mkdir docker_releases

set -x
./docker/docker_compile_release && \
  cp docker/release/whats_where_release.zip ./ && \
  docker build -f docker/deploy/Dockerfile -t ${tag_name} . && \
  docker tag ${tag_name} ${image_name} && \
  docker push ${image_name}

set +x

mkdir docker_releases/${tag}
echo "${compose_file_string/SUBSTITUTE_RELEASE_IMAGE_NAME_HERE/$image_name}" > docker_releases/${tag}/docker-compose.yml
