#!/bin/bash

rm -f ./docker/testing/development_status_report.zip

docker-compose -f docker/testing/docker-compose.yml build whats_where_test_runner
docker-compose -f docker/testing/docker-compose.yml run --rm whats_where_test_runner ./testing_status_report
