version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/scripts/whats_where
permissions:
  - object: /home/ubuntu/scripts/whats_where
    pattern: "deploy"
    mode: 755
hooks:
# During the ApplicationStart deployment lifecycle event, run the commands
#   in the script specified in "location".
  ApplicationStart:
    - location: deploy_whats_where
      timeout: 600
      runas: ubuntu