version: '3.1'

services:
  yellr_server:
    image: SUBSTITUTE_RELEASE_IMAGE_NAME_HERE
    command: "/bin/bash -cl /home/elixir/whats_where/start_server"
    environment:
      - DATABASE_HOST=whats_where_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - HOST=SUBSTITUTE_DEPLOY_HOST_NAME_HERE
      - PORT=8080
      - API_KEY=DEPLOYMENT_TEST_API_KEY
    depends_on:
      - whats_where_db
    links:
      - whats_where_db
    ports:
      - 9500:8080
  whats_where_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: